name: Build IPK

on:
  release:
    types: published
  push:
    branches:
      - main
# 每天触发一次
  schedule:
    - cron: '0 0 * * *'
  watch:
    types: started
  workflow_dispatch:
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 下载 openwrt sdk
        run: |
          wget https://downloads.openwrt.org/releases/22.03.5/targets/x86/generic/openwrt-sdk-22.03.5-x86-generic_gcc-11.2.0_musl.Linux-x86_64.tar.xz
          tar -xf openwrt-sdk-22.03.5-x86-generic_gcc-11.2.0_musl.Linux-x86_64.tar.xz
      - name: 更新软件源
        run: |
          cd openwrt-sdk-22.03.5-x86-generic_gcc-11.2.0_musl.Linux-x86_64
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      - name: 编译
        run: |
          cd openwrt-sdk-22.03.5-x86-generic_gcc-11.2.0_musl.Linux-x86_64
          cd package/
          git clone https://github.com/pppoex/openwrt-packages
          cd ..
          wget https://raw.githubusercontent.com/pppoex/openwrt-packages_action/main/start-build.py
          wget https://raw.githubusercontent.com/pppoex/openwrt-packages_action/main/build.sh
          python3 build.py

      - name: 利用上传工件模块上传所有ipk文件
        uses: actions/upload-artifact@v2
        with:
          name: ipk
          path: openwrt-sdk-22.03.5-x86-generic_gcc-11.2.0_musl.Linux-x86_64/bin/targets/x86/generic/
          if-no-files-found: error
